# Generated by Django 4.2 on 2025-11-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('titulo_alternativo', models.CharField(blank=True, max_length=255, null=True)),
                ('animeflv_id', models.CharField(max_length=100, unique=True)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('episodios_totales', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('En emisión', 'En emisión'), ('Finalizado', 'Finalizado'), ('Próximamente', 'Próximamente')], default='En emisión', max_length=20)),
                ('puntuacion', models.FloatField(default=0.0)),
                ('url_poster', models.URLField(blank=True, null=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
            ],
            options={
                'verbose_name_plural': 'Animes',
                'db_table': 'animes',
            },
        ),
    ]
