# Generated by Django 4.2 on 2025-11-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(max_length=100)),
                ('episodio_actual', models.IntegerField(default=0)),
                ('visto_completo', models.BooleanField(default=False)),
                ('mi_calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('estado', models.CharField(choices=[('Viendo', 'Viendo'), ('Completado', 'Completado'), ('Pendiente', 'Pendiente'), ('Abandonado', 'Abandonado')], default='Pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
            ],
            options={
                'verbose_name_plural': 'Mi Lista',
                'db_table': 'mi_lista',
                'unique_together': {('anime', 'usuario_nombre')},
            },
        ),
    ]
