# Generated by Django 4.2 on 2025-11-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_lista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milista',
            name='episodios_vistos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='milista',
            name='ultimo_episodio_visto',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
