# Generated by Django 4.2 on 2025-11-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color_hex', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
            },
        ),
    ]
